---
name: bookly_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.0.0
  go_router: ^11.0.0
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: GT Sectra Fine
    fonts:
    - asset: assets/fonts/GT Sectra Fine Regular.ttf
